package com.inventory.controller;

import com.inventory.DataAccessObject.ProductDAO;
import com.inventory.model.product;
import com.inventory.service.EmailService;
import com.inventory.util.CSVHelper;
import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

import java.io.File;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class ReportsController {
    
    @FXML private TextField txtRecipientEmail;
    @FXML private TextField txtEmailSubject;
    @FXML private TextArea txtEmailMessage;
    @FXML private TextField txtAttachmentPath;
    @FXML private Label lblReportStatus;
    @FXML private Label lblEmailStatus;
    @FXML private ListView<String> reportHistoryList;
    
    private ProductDAO productDAO;
    private String currentUsername;
    private String currentUserEmail;
    private String lastGeneratedReportPath;
    
    @FXML
    public void initialize() {
        productDAO = new ProductDAO();
        txtEmailMessage.setText("Hello,\n\nPlease find the attached inventory report.\n\nRegards,\nInventory Management System");
        loadReportHistory();
    }
    
    public void setUserInfo(String username, String email) {
        this.currentUsername = username;
        this.currentUserEmail = email;
        // Pre-fill recipient email with user's email
        if (txtRecipientEmail != null && email != null) {
            txtRecipientEmail.setText(email);
        }
    }
    
    @FXML
    private void onGenerateCSVReport() {
        try {
            List<product> products = productDAO.getAllProducts();
            
            if (products.isEmpty()) {
                showAlert(Alert.AlertType.WARNING, "No Products", 
                    "No products available to generate report.");
                return;
            }
            
            String filePath = CSVHelper.generateReport(products, currentUsername != null ? currentUsername : "Admin");
            
            if (filePath != null) {
                lastGeneratedReportPath = filePath;
                txtAttachmentPath.setText(filePath);
                lblReportStatus.setText("✅ Report generated successfully: " + new File(filePath).getName());
                lblReportStatus.setStyle("-fx-text-fill: #27ae60;");
                
                // Add to history
                addToHistory("Generated: " + new File(filePath).getName());
                
                showAlert(Alert.AlertType.INFORMATION, "Success", 
                    "Report generated successfully!\nSaved at: " + filePath);
            } else {
                lblReportStatus.setText("❌ Failed to generate report.");
                lblReportStatus.setStyle("-fx-text-fill: #e74c3c;");
            }
            
        } catch (Exception e) {
            lblReportStatus.setText("❌ Error: " + e.getMessage());
            lblReportStatus.setStyle("-fx-text-fill: #e74c3c;");
            e.printStackTrace();
        }
    }
    
    @FXML
    private void onPreviewReport() {
        try {
            List<product> products = productDAO.getAllProducts();
            
            if (products.isEmpty()) {
                showAlert(Alert.AlertType.WARNING, "No Products", 
                    "No products available to preview.");
                return;
            }
            
            StringBuilder preview = new StringBuilder("📊 INVENTORY REPORT PREVIEW\n");
            preview.append("=".repeat(50)).append("\n\n");
            preview.append("Generated By: ").append(currentUsername != null ? currentUsername : "Admin").append("\n");
            preview.append("Generated On: ").append(LocalDateTime.now().format(
                DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))).append("\n");
            preview.append("=".repeat(50)).append("\n\n");
            
            preview.append(String.format("%-5s %-20s %-15s %-10s %-12s %-15s\n", 
                "ID", "Name", "Category", "Quantity", "Price", "Stock Value"));
            preview.append("-".repeat(80)).append("\n");
            
            final double[] totalValue = {0};
            final int[] lowStockCount = {0};
            
            for (product p : products) {
                double stockValue = p.getQuantity() * p.getPrice();
                totalValue[0] += stockValue;
                int threshold = p.getThreshold() > 0 ? p.getThreshold() : 10;
                if (p.getQuantity() < threshold) {
                    lowStockCount[0]++;
                }
                
                preview.append(String.format("%-5d %-20s %-15s %-10d ₹%-11.2f ₹%-14.2f\n",
                    p.getId(), p.getName(), p.getCategory(), p.getQuantity(), 
                    p.getPrice(), stockValue));
            }
            
            preview.append("-".repeat(80)).append("\n");
            preview.append(String.format("Total Products: %d\n", products.size()));
            preview.append(String.format("Low Stock Items: %d\n", lowStockCount[0]));
            preview.append(String.format("Total Stock Value: ₹%.2f\n", totalValue[0]));
            
            // Show preview in dialog
            TextArea previewArea = new TextArea(preview.toString());
            previewArea.setEditable(false);
            previewArea.setPrefRowCount(20);
            previewArea.setPrefColumnCount(80);
            
            Dialog<Void> dialog = new Dialog<>();
            dialog.setTitle("Report Preview");
            dialog.setHeaderText("Inventory Report Preview");
            dialog.getDialogPane().setContent(previewArea);
            dialog.getDialogPane().getButtonTypes().add(ButtonType.CLOSE);
            dialog.showAndWait();
            
        } catch (Exception e) {
            showAlert(Alert.AlertType.ERROR, "Error", 
                "Failed to generate preview: " + e.getMessage());
        }
    }
    
    @FXML
    private void onSendReportEmail() {
        String recipient = txtRecipientEmail.getText().trim();
        String subject = txtEmailSubject.getText().trim();
        String message = txtEmailMessage.getText().trim();
        String attachment = txtAttachmentPath.getText().trim();
        
        // Validation
        if (recipient.isEmpty() || !recipient.contains("@")) {
            showAlert(Alert.AlertType.WARNING, "Invalid Email", 
                "Please enter a valid recipient email address.");
            return;
        }
        
        if (subject.isEmpty()) {
            subject = "📦 Inventory Report";
        }
        
        if (message.isEmpty()) {
            message = "Please find the attached inventory report.";
        }
        
        if (attachment.isEmpty()) {
            // Generate report if not already generated
            onGenerateCSVReport();
            attachment = lastGeneratedReportPath;
            if (attachment == null || attachment.isEmpty()) {
                showAlert(Alert.AlertType.WARNING, "No Attachment", 
                    "Please generate a report first or select an attachment file.");
                return;
            }
        }
        
        // Check if file exists
        File attachmentFile = new File(attachment);
        if (!attachmentFile.exists()) {
            showAlert(Alert.AlertType.WARNING, "File Not Found", 
                "Attachment file not found: " + attachment);
            return;
        }
        
        // Make variables final for use in lambda
        final String finalRecipient = recipient;
        final String finalSubject = subject;
        final String finalMessage = message;
        final String finalAttachment = attachment;
        
        // Send email in background thread
        lblEmailStatus.setText("Sending email...");
        lblEmailStatus.setStyle("-fx-text-fill: #3498db;");
        
        new Thread(() -> {
            try {
                EmailService.sendReport(finalRecipient, finalSubject, finalMessage, finalAttachment);
                
                javafx.application.Platform.runLater(() -> {
                    lblEmailStatus.setText("✅ Email sent successfully to " + finalRecipient);
                    lblEmailStatus.setStyle("-fx-text-fill: #27ae60;");
                    addToHistory("Email sent to: " + finalRecipient + " at " + 
                        LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss")));
                    showAlert(Alert.AlertType.INFORMATION, "Success", 
                        "Report email sent successfully to " + finalRecipient);
                });
                
            } catch (Exception e) {
                final String errorMessage = e.getMessage();
                javafx.application.Platform.runLater(() -> {
                    lblEmailStatus.setText("❌ Failed to send email: " + errorMessage);
                    lblEmailStatus.setStyle("-fx-text-fill: #e74c3c;");
                    showAlert(Alert.AlertType.ERROR, "Error", 
                        "Failed to send email: " + errorMessage);
                });
            }
        }).start();
    }
    
    @FXML
    private void onTestEmail() {
        String recipient = txtRecipientEmail.getText().trim();
        
        if (recipient.isEmpty() || !recipient.contains("@")) {
            showAlert(Alert.AlertType.WARNING, "Invalid Email", 
                "Please enter a valid recipient email address for testing.");
            return;
        }
        
        final String finalRecipient = recipient;
        
        lblEmailStatus.setText("Sending test email...");
        lblEmailStatus.setStyle("-fx-text-fill: #3498db;");
        
        new Thread(() -> {
            try {
                EmailService.sendReport(finalRecipient, "Test Email - Inventory System", 
                    "This is a test email from the Inventory Management System.", null);
                
                javafx.application.Platform.runLater(() -> {
                    lblEmailStatus.setText("✅ Test email sent successfully!");
                    lblEmailStatus.setStyle("-fx-text-fill: #27ae60;");
                    showAlert(Alert.AlertType.INFORMATION, "Success", 
                        "Test email sent successfully to " + finalRecipient);
                });
                
            } catch (Exception e) {
                final String errorMessage = e.getMessage();
                javafx.application.Platform.runLater(() -> {
                    lblEmailStatus.setText("❌ Test email failed: " + errorMessage);
                    lblEmailStatus.setStyle("-fx-text-fill: #e74c3c;");
                    showAlert(Alert.AlertType.ERROR, "Error", 
                        "Failed to send test email: " + errorMessage);
                });
            }
        }).start();
    }
    
    @FXML
    private void onBrowseAttachment() {
        FileChooser fileChooser = new FileChooser();
        fileChooser.setTitle("Select Report File");
        fileChooser.getExtensionFilters().add(
            new FileChooser.ExtensionFilter("CSV Files", "*.csv"));
        fileChooser.getExtensionFilters().add(
            new FileChooser.ExtensionFilter("Text Files", "*.txt"));
        fileChooser.getExtensionFilters().add(
            new FileChooser.ExtensionFilter("All Files", "*.*"));
        
        Stage stage = (Stage) txtAttachmentPath.getScene().getWindow();
        File selectedFile = fileChooser.showOpenDialog(stage);
        
        if (selectedFile != null) {
            txtAttachmentPath.setText(selectedFile.getAbsolutePath());
            lastGeneratedReportPath = selectedFile.getAbsolutePath();
        }
    }
    
    private void loadReportHistory() {
        // Load report history from reports directory
        try {
            File reportsDir = new File("reports");
            if (reportsDir.exists() && reportsDir.isDirectory()) {
                File[] reportFiles = reportsDir.listFiles((dir, name) -> 
                    name.toLowerCase().endsWith(".csv"));
                
                if (reportFiles != null && reportFiles.length > 0) {
                    for (File file : reportFiles) {
                        addToHistory("Report: " + file.getName());
                    }
                }
            }
        } catch (Exception e) {
            // Ignore errors in loading history
        }
    }
    
    private void addToHistory(String entry) {
        if (reportHistoryList != null) {
            String timestamp = LocalDateTime.now().format(
                DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
            reportHistoryList.getItems().add(0, "[" + timestamp + "] " + entry);
            
            // Keep only last 20 entries
            if (reportHistoryList.getItems().size() > 20) {
                reportHistoryList.getItems().remove(
                    reportHistoryList.getItems().size() - 1);
            }
        }
    }
    
    private void showAlert(Alert.AlertType type, String title, String message) {
        Alert alert = new Alert(type);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}

